### PR TITLE
resolve compiler error:bumo-encryption jar not found

### PR DESCRIPTION
**Pull request by catinred2**
local dependency leads to unstable build

### CODE REVIEW

**Comment by frm430342210** [comment]
Did you add the remote repository of maven

**Comment by frm430342210** [comment]
If you did add the remote repository of maven, it would be right.

**Comment by catinred2** [comment]
local dependency is unstable.  maven build would fail with the message "Could not find artifact io.bumo:bumo-encryption:jar:1.0.1" . you have to config the jar files under "lib" directory as external dependency through some IDE (such as Eclipse, IntelliJ ,etc).  it is not proper that someone have to use some IDE to build the project.

**Comment by frm430342210** [comment]
> local dependency is unstable. maven build would fail with the message "Could not find artifact io.bumo:bumo-encryption:jar:1.0.1" . you have to config the jar files under "lib" directory as external dependency through some IDE (such as Eclipse, IntelliJ ,etc). it is not proper that someone have to use some IDE to build the project.
The bumo-encryption has been updated to 1.0.6. please using bumo-encryption-1.0.6.jar. Thanks!

**Comment by frm430342210** [comment]
> local dependency is unstable. maven build would fail with the message "Could not find artifact io.bumo:bumo-encryption:jar:1.0.1" . you have to config the jar files under "lib" directory as external dependency through some IDE (such as Eclipse, IntelliJ ,etc). it is not proper that someone have to use some IDE to build the project.

do you set your repository as follow?
<repositories>
		<repository>
			<id>pubnexus</id>
			<url>http://maven.bumo.io/content/groups/public/</url>
			<releases>
				<enabled>true</enabled>
			</releases>
			<snapshots>
				<enabled>true</enabled>
			</snapshots>
		</repository>
	</repositories>

Now the bumo-encryption has been updated to 1.0.6 in libs. But the 1.0.1 can be used again in maven. please trying again. Thans for your question.

**Comment by frm430342210** [comment]
> local dependency is unstable. maven build would fail with the message "Could not find artifact io.bumo:bumo-encryption:jar:1.0.1" . you have to config the jar files under "lib" directory as external dependency through some IDE (such as Eclipse, IntelliJ ,etc). it is not proper that someone have to use some IDE to build the project.

do you set your repository as follow?
<repository>
    <id>pubnexus</id>                
    <url>http://maven.bumo.io/content/groups/public/</url>
    <releases>
        <enabled>true</enabled>
    </releases>
    <snapshots>
        <enabled>true</enabled>
    </snapshots>
</repository>

Now the bumo-encryption has been updated to 1.0.6 in libs. But the 1.0.1 can be used again in maven. please trying again. Thans for your question.

**Comment by frm430342210** [comment]
> local dependency is unstable. maven build would fail with the message "Could not find artifact io.bumo:bumo-encryption:jar:1.0.1" . you have to config the jar files under "lib" directory as external dependency through some IDE (such as Eclipse, IntelliJ ,etc). it is not proper that someone have to use some IDE to build the project.

do you set your repository as follow?

```
<repository>
    <id>pubnexus</id>                
    <url>http://maven.bumo.io/content/groups/public/</url>
    <releases>
        <enabled>true</enabled>
    </releases>
    <snapshots>
        <enabled>true</enabled>
    </snapshots>
</repository>
```

Now the bumo-encryption has been updated to 1.0.6 in libs. But the 1.0.1 can be used again in maven. please trying again. Thans for your question.

**Pull request closed without merging**
